version: '2'
services:
  db:
    container_name: db-container
    build:
      context: ./db
      args:
        NEW_NEO4J_PASSWD: neopasswd
    restart: always
    ports:
        - "17473:7473"
        - "17474:7474"
        - "17687:7687"
    volumes:
        - ./neo4j.conf:/etc/neo4j/neo4j.conf
    networks:
      - internal

  webapp:
    container_name: webapp-container
    build: ./webapp
    ports:
        - "8080:8080"
    volumes:
        - ./cinema-app.properties:/var/lib/cinema-app/cinema-app.properties
    networks:
      - internal

networks:
  internal:
    driver: 'bridge'
