version: '2'
services:
  db:
    container_name: db-container
    build:
      context: ./db
    restart: always
    # uncomment to check db in web browser
    # ports:
    #     - "17473:7473"
    #     - "17474:7474"
    #     - "17687:7687"
    volumes:
        - ./db/data:/var/lib/neo4j/data
    networks:
      - internal

  webapp:
    container_name: webapp-container
    build: ./webapp
    ports:
        - "8080:8080"
    volumes:
        - ./webapp/cinema-app.properties:/var/lib/cinema-app/cinema-app.properties
    networks:
      - internal

networks:
  internal:
    driver: 'bridge'
